on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.gh_token }}
          release-type: node
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - run: pnpm build
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.releases_created == 'true' }}
